# Demo secrets.yaml You should really change this 

wifi_ssid: PfizerModerna-5G
wifi_password: "**********"
api_password: "SecureOTAandAPI-password"

esphome_web_server_password: "WachtwoordWebserver"
